version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=supplychain
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=supplychain_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  llm:
    image: ghcr.io/huggingface/text-generation-inference:latest
    environment:
      - MODEL_ID=/models/flan-t5-base
      - DEVICE=gpu
    ports:
      - "8080:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./models:/models
    networks:
      - sc_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://supplychain:password@postgres:5432/supplychain_db
      - TGI_URL=http://llm:80/generate
      - LOCAL_SENTENCE_VARIABLE_MODEL_DIR=/models/sentence-transformers/all-MiniLM-L6-v2
    restart: on-failure
    volumes:
      - ./backend:/app
      - ./models:/models
    networks:
      - sc_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_ENDPOINT=http://ai-supplychain-backend-1:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - ./models:/models
    networks:
      - sc_network

volumes:
  postgres_data:

networks:
  sc_network:
    driver: bridge
